version: '3.8'

services:
  api:
    build: .
    container_name: tao_api
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0

  worker:
    build: .
    container_name: tao_celery_worker
    command: celery -A tasks.worker worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0

  scheduler:
    build: .
    container_name: tao_celery_scheduler
    command: celery -A tasks.scheduler beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - worker
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0

  redis:
    image: redis:7
    container_name: tao_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: tao_user
      POSTGRES_PASSWORD: tao_pass
      POSTGRES_DB: tao_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tao_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
